name: Docker-based Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image for CI
        run: |
          docker build \
            --build-arg TARGET=ci \
            --file Dockerfile \
            --target ci \
            --tag dia-llm-ci \
            .

      - name: Run container and verify setup
        run: |
          docker run --rm dia-llm-ci python3 -c "print('Docker CI is working')"
